#!/usr/bin/env sh

# variables - Color ANSI escape codes, see https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
CYAN='\033[0;36m' 
PURPLE='\033[0;35m' 
NC='\033[0m' # No Color

# Content
echo "Pre-push hook"
echo "Running tests on changed files"
npm run test-changes
echo "App will be deployed to fly.io using git action, follow deployment at https://github.com/ben-perrier/polka-ui/actions/"
echo "> ${CYAN}Github action deployment:${NC} https://github.com/ben-perrier/polka-ui/actions/"
echo "> ${PURPLE}Fly app activity:${NC} https://fly.io/apps/polka-ui/activity"
echo "> ${PURPLE}Fly app logs:${NC} https://fly.io/apps/polka-ui/monitoring"